/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cart = Array<CartItem>;
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface CustomSticker {
  'id' : bigint,
  'creator' : Principal,
  'name' : string,
  'description' : [] | [string],
  'category' : StickerCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'items' : Cart,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'googlePay' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'tableTennisBalls' : null } |
  { 'badmintonShuttles' : null };
export type StickerCategory = { 'patterns' : null } |
  { 'food' : null } |
  { 'animals' : null } |
  { 'sports' : null } |
  { 'cartoon' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, ProductCategory, bigint],
    [] | [bigint]
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[PaymentMethod, string], bigint>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCustomSticker' : ActorMethod<
    [ExternalBlob, bigint, string, StickerCategory, [] | [string]],
    CustomSticker
  >,
  'getAllCustomStickers' : ActorMethod<[], Array<CustomSticker>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerCustomStickers' : ActorMethod<[], Array<CustomSticker>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCustomSticker' : ActorMethod<[bigint], [] | [CustomSticker]>,
  'getCustomStickersByUser' : ActorMethod<[Principal], Array<CustomSticker>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, ProductCategory, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];